# Generated by Django 3.0.8 on 2020-08-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactu',
            name='email',
            field=models.EmailField(default='contact@jigyasha.com', max_length=254),
        ),
    ]
