# Generated by Django 3.0.8 on 2020-08-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactu_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactu',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
