# Generated by Django 3.0.8 on 2020-08-19 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0006_auto_20200818_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('company_name', models.CharField(blank=True, max_length=75, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(default='Nepal', max_length=10)),
                ('province', models.CharField(max_length=10)),
                ('district', models.CharField(blank=True, max_length=25, null=True)),
                ('city', models.CharField(max_length=25)),
                ('address_line_01', models.CharField(max_length=25)),
                ('address_line_02', models.CharField(blank=True, max_length=25, null=True)),
                ('zip_code', models.CharField(max_length=10)),
                ('order_notes', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
