# Generated by Django 3.0.8 on 2020-08-14 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], max_length=10)),
                ('slug', models.SlugField(max_length=75, unique=True)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='products/cover_images')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products/images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/images')),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('ratings_quantity', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
