# Generated by Django 3.0.8 on 2020-08-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=20)),
                ('information', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='team')),
            ],
        ),
    ]
