# Generated by Django 3.0.8 on 2020-08-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium_text', models.CharField(max_length=25)),
                ('large_text1', models.CharField(max_length=15)),
                ('large_text2', models.CharField(max_length=15)),
                ('small_text', models.CharField(max_length=50)),
            ],
        ),
    ]
