# Generated by Django 3.0.8 on 2020-08-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_auto_20200804_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='large_text1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='banner',
            name='large_text2',
            field=models.CharField(max_length=15),
        ),
    ]
