# Generated by Django 3.0.8 on 2020-08-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20200806_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='subtotal_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
