# Generated by Django 3.0.8 on 2020-08-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_auto_20200816_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.IntegerField(default=39),
        ),
    ]
